### ISSUE TITLE
ничего не работает 

### ISSUE THREAD

**Issue by rongirl** [true-real-michael/cpp-hw#3]
Здравствуйте, тру-рил-майкл! Я запускаю ваш банкерс алгоритм и чето не робит, я может чето не так делаю? Я вот скачала вроде поставила но чето не работает может быть проблема у меня я сижу на linux (уьунту) у миня еще dota 2 запущена это влияет как-то не знаете? Также у меня работает видео гайд как запустить банкерс алогортм сылка вот https://www.youtube.com/watch?v=PvU805XD8tk&t=3s помогите пожалуйста

**Comment by true-real-michael** [comment]
> Здравствуйте, тру-рил-майкл! Я запускаю ваш банкерс алгоритм и чето не робит, я может чето не так делаю? Я вот скачала вроде поставила но чето не работает может быть проблема у меня я сижу на linux (уьунту) у миня еще dota 2 запущена это влияет как-то не знаете? Также у меня работает видео гайд как запустить банкерс алогортм сылка вот https://www.youtube.com/watch?v=PvU805XD8tk&t=3s помогите пожалуйста


Hello, rongirl! Thanks for your interest in my project.

It's sad to head that you could not run the project. We are currently working on linux (уьунту) out-of-the-box support. Dota 2 support, however, is not in our roadmap in the foreseeable future. Perhaps, other guides may help you running the algorithm

take a look at: [video](https://www.youtube.com/watch?v=PEUIqiBAaQw&list=PLQB7jzYVnlkoITMgvJlrE-kySAgCVg2ua&index=29) and [video (has a russian version)](https://www.youtube.com/watch?v=ZJ0zJDz1G1M)
